Vytvoření základní logiky a frontendu skladu
ondrejkozel/zaurex-management pull request #5
Opened 2022-03-20 12:15 UTC by ondrejkozel

2022-03-21 20:14 UTC, ondrejkozel commented on src/main/java/cz/wildwest/zaurex/components/gridd/Gridd.java
> +                    hasValueAndElement.setReadOnly(true);
Nějak jsem udělal pohled prodavače, který může pouze zobrazovat zboží, ne upravovat.  Nevypadá to nejlíp, ty inputy mají prostě jen zakázané úpravy, ale tlačí nás čas, takže to teď lépe neudělám :(
Co na to říkáš, @PapirovyBukanyr ?

2022-03-22 08:03 UTC, PapirovyBukanyr commented on src/main/java/cz/wildwest/zaurex/data/entity/WarehouseItem.java
> +public class WarehouseItem extends AbstractEntity {
Přidat ještě atribut poznámka, resp. velikost.

2022-03-22 20:39 UTC, ondrejkozel commented
Dodělal jsem správu variant, @PapirovyBukanyr, můžeš to pořádně otestovat.

2022-03-23 14:09 UTC, ondrejkozel commented
Tak sklad je už asi hotovej. Nefunguje řazení prvků v gridu, netuším proč. Holt to budeme muset oželet, prozatím.
Až se na to podíváš a otestuješ, můžeš mergnout tento pull request. @PapirovyBukanyr

2022-03-24 07:46 UTC, PapirovyBukanyr requested changes
Při odstraňování položky ze skladu se neodstraní jeho varianty, a tak operace selže kvůli cizím klíčům. @ondrejkozel

2022-03-25 22:25 UTC, merged